"""Add QuizPass.current_item_index

Revision ID: 0c3ed0c592e2
Revises: a8927d96dfd6
Create Date: 2019-03-02 22:42:47.240662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3ed0c592e2'
down_revision = 'a8927d96dfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizpass', sa.Column('current_item_index', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizpass', 'current_item_index')
    # ### end Alembic commands ###
