"""Add answer data into QuizItem

Revision ID: c34791b2d821
Revises: 0c3ed0c592e2
Create Date: 2019-03-03 15:05:42.117063

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'c34791b2d821'
down_revision = '0c3ed0c592e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizitem', sa.Column('answered_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True))
    op.add_column('quizitem', sa.Column('given_answer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizitem', 'given_answer')
    op.drop_column('quizitem', 'answered_at')
    # ### end Alembic commands ###
