class BaseConfig:
    # Bot token generated by the Bot Father.
    # The first required config var.
    BOT_TOKEN = None

    # ID of the group, bot will be gate-keeping, `int`.
    # The second and the last required config var.
    GROUP_ID = None

    # Proxy URL for the bot's requests, if necessary.
    # E.g. 'socks5://127.0.0.1:9050'
    PROXY_URL = None

    # Database URL for SQLAlchemy
    SQLALCHEMY_URL = 'sqlite:///gatebot.db'

    # Path to the json file, containing questions and answers for the quizzes.
    QUESTIONS_FILE = 'questions.json'

    # How many questions are selected for a single quiz pass?
    QUESTIONS_PER_QUIZ = 20

    # How many correct answers does user have to present to pass the test?
    CORRECT_ANSWERS_REQUIRED = 11
