from datetime import timedelta


class BaseConfig:
    #
    # Required params
    #

    # Bot token generated by the Bot Father.
    BOT_TOKEN = None

    # ID of the group, bot will be gate-keeping, as `int`.
    GROUP_ID = None

    # Database URL for SQLAlchemy
    SQLALCHEMY_URL = 'postgresql://username:password@host:port/db'

    #
    # Optional params
    #

    # Proxy URL for the bot's requests, if necessary.
    # E.g. 'socks5://127.0.0.1:9050'
    PROXY_URL = None

    # Path to the json file, containing questions and answers for the quizzes.
    QUESTIONS_FILE = 'questions.json'

    # How many questions are selected for a single quiz pass?
    QUESTIONS_PER_QUIZ = 20

    # How many correct answers does user have to present to pass the test?
    CORRECT_ANSWERS_REQUIRED = 11

    # How many hours does user have to wait after failing the quiz
    # to try again?
    WAIT_HOURS_ON_FAIL = 72

    # After what time period newly-joined user will kicked if they
    # haven't started the quiz?
    KICK_INACTIVE_AFTER = timedelta(minutes=15)

    # Delete join and leave messages
    DELETE_JOIN_MESSAGES = True
    DELETE_LEAVE_MESSAGES = True
